### PR TITLE
PR for Changed some styles

### PR DESCRIPTION
**Pull request by gopalbbharadva**
Description:
- I changed some styles of grid and responsiveness.
- Also added that quantity count feature.
- Click on cart button to reach out to changes.

### CODE REVIEW

**Comment by poornima-alugubelly** [comment]
Hi gopal in cart page the scrolling is stopping at a point and the card is getting cut off , might want to check on that
image

**Review by poornima-alugubelly — APPROVED** [review]

**Review by himadri2110 — APPROVED** [review]
Looks good!

**Comment by gopalbbharadva** [comment]
> Hi gopal in cart page the scrolling is stopping at a point and the card is getting cut off , might want to check on that image

are you talking about vertical scrolling?

**Comment by gopalbbharadva** [comment]
> Hi gopal in cart page the scrolling is stopping at a point and the card is getting cut off , might want to check on that image

Maybe, that netlify footer thing you talking about.

**Comment by gopalbbharadva** [comment]
> > Hi gopal in cart page the scrolling is stopping at a point and the card is getting cut off , might want to check on that image
> 
> Maybe, that netlify footer thing you talking about. I tried in different browser and incongnito window it's working fine.

**Pull request merged**
